# simple workflow to deploy static content to Pages
name: Deploy static site to Pages

on:
  push:
    branches: ["main"]

  # allows this workflow to be ran manually, from the Actions tab
  workflow_dispatch:

# sets workflow permissions to allow Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# allow only one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./public"
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
